name: Release Zipper

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Set up Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Set version
        run: mvn versions:set -DnewVersion=${{ env.VERSION }} -DVERSION=${{ env.VERSION }} -DgenerateBackupPoms=false

      - name: Publish to Maven Central
        run: mvn clean deploy -DskipTests --batch-mode
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Zip src directory
        working-directory: ./src
        run: zip -r ../fix-message-${{ env.VERSION }}.zip . -x "favicon.ico" "index.html" "fix-decoder.svg"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fix-message-${{ env.VERSION }}.zip
          asset_name: fix-message-${{ env.VERSION }}.zip
          asset_content_type: application/zip
